"""empty message

Revision ID: 0148cb86170e
Revises: 598ae3bd0255
Create Date: 2020-02-21 15:51:45.929869

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0148cb86170e'
down_revision = '598ae3bd0255'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'book', ['label'])
    op.create_unique_constraint(None, 'book', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'book', type_='unique')
    op.drop_constraint(None, 'book', type_='unique')
    # ### end Alembic commands ###
