"""empty message

Revision ID: 4fa33e500d02
Revises: 0148cb86170e
Create Date: 2020-02-25 15:14:00.522088

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4fa33e500d02'
down_revision = '0148cb86170e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=140), nullable=True),
    sa.Column('author', sa.String(length=64), nullable=True),
    sa.Column('label', sa.String(length=16), nullable=True),
    sa.Column('subject', sa.String(length=64), nullable=True),
    sa.Column('holder', sa.Integer(), nullable=True),
    sa.Column('shelf', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['holder'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('label'),
    sa.UniqueConstraint('title')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('book')
    # ### end Alembic commands ###
