"""books table

Revision ID: 598ae3bd0255
Revises: 7e224d3d65c1
Create Date: 2020-02-21 15:40:12.697319

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '598ae3bd0255'
down_revision = '7e224d3d65c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('book', 'author',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.alter_column('book', 'label',
               existing_type=sa.VARCHAR(length=16),
               nullable=False)
    op.alter_column('book', 'name',
               existing_type=sa.VARCHAR(length=140),
               nullable=False)
    op.create_unique_constraint(None, 'book', ['label'])
    op.create_unique_constraint(None, 'book', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'book', type_='unique')
    op.drop_constraint(None, 'book', type_='unique')
    op.alter_column('book', 'name',
               existing_type=sa.VARCHAR(length=140),
               nullable=True)
    op.alter_column('book', 'label',
               existing_type=sa.VARCHAR(length=16),
               nullable=True)
    op.alter_column('book', 'author',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    # ### end Alembic commands ###
