"""books table

Revision ID: 7e224d3d65c1
Revises: 81c462cda27d
Create Date: 2020-02-21 15:36:04.518499

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e224d3d65c1'
down_revision = '81c462cda27d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('label', sa.String(length=16), nullable=True))
    op.add_column('book', sa.Column('shelf', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('book', 'shelf')
    op.drop_column('book', 'label')
    # ### end Alembic commands ###
