"""books table

Revision ID: 81c462cda27d
Revises: 2c615fce6ba2
Create Date: 2020-02-17 17:20:41.618406

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81c462cda27d'
down_revision = '2c615fce6ba2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=140), nullable=True),
    sa.Column('author', sa.String(length=64), nullable=True),
    sa.Column('holder', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['holder'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('book')
    # ### end Alembic commands ###
