"""empty message

Revision ID: c4faf5ebf23a
Revises: 2f5c31804149
Create Date: 2020-03-12 14:51:23.576186

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4faf5ebf23a'
down_revision = '2f5c31804149'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('desk',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('x', sa.Float(), nullable=True),
    sa.Column('y', sa.Float(), nullable=True),
    sa.Column('angle', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_desk_x'), 'desk', ['x'], unique=False)
    op.create_table('shelf',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('x', sa.Float(), nullable=True),
    sa.Column('y', sa.Float(), nullable=True),
    sa.Column('angle', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shelf_x'), 'shelf', ['x'], unique=False)
    op.create_foreign_key(None, 'book', 'shelf', ['shelf'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'book', type_='foreignkey')
    op.drop_index(op.f('ix_shelf_x'), table_name='shelf')
    op.drop_table('shelf')
    op.drop_index(op.f('ix_desk_x'), table_name='desk')
    op.drop_table('desk')
    # ### end Alembic commands ###
